name: syndata
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7.12
  - matplotlib=3.4.3
  - numpy=1.19.5
  - pandas=1.3.3
  - scikit-learn=1.0
  - scipy=1.7.1
  - seaborn=0.11.2
  - tensorflow=1.15.0
  - tensorflow-probability=0.7.0